# Generated by Django 6.0.6 on 2026-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
