# Generated by Django 6.0.6 on 2026-07-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_options_remove_menuitem_image_url_and_more'),
        ('restaurants', '0004_restaurant_review_count'),
    ]

    operations = [
    ]
