# Generated by Django 6.0.7 on 2026-08-10 11:12

import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_merge_20260723_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/%Y/%m/', validators=[restaurants.validators.validate_image_extension, restaurants.validators.validate_image_size, restaurants.validators.validate_image_integrity]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/%Y/%m/', validators=[restaurants.validators.validate_image_extension, restaurants.validators.validate_image_size, restaurants.validators.validate_image_integrity]),
        ),
    ]
