# Generated by Django 6.0.7 on 2026-08-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_menuitem_price'),
        ('restaurants', '0006_menuitem_image_url_restaurant_image_and_more'),
    ]

    operations = [
    ]
