# Generated by Django 6.0.6 on 2026-09-14 10:28

import restaurants.models
import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_retire_placeholder_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.menu_item_image_upload_path, validators=[restaurants.validators.validate_image_extension, restaurants.validators.validate_image_size, restaurants.validators.validate_image_integrity]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.restaurant_image_upload_path, validators=[restaurants.validators.validate_image_extension, restaurants.validators.validate_image_size, restaurants.validators.validate_image_integrity]),
        ),
    ]
