# Generated by Django 6.0.6 on 2026-09-19 10:28

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_expand_media_filename_capacity'),
    ]

    operations = [
        pgvector.django.VectorExtension()
    ]
