# Generated by Django 6.0.6 on 2026-09-19 10:29

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_embedding_stale',
            field=models.BooleanField(default=True),
        ),
    ]
