# Generated by Django 6.0.6 on 2026-08-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_latitude_order_delivery_longitude'),
        ('orders', '0004_remove_order_delivery_address_order_apartment_and_more'),
    ]

    operations = [
    ]
