# Generated by Django 6.0.6 on 2026-08-30 16:45

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_delivery_address_order_apartment_and_more'),
        ('restaurants', '0007_merge_20260812_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_latitude__isnull', True), ('delivery_longitude__isnull', True)), models.Q(('delivery_latitude__isnull', False), ('delivery_longitude__isnull', False)), _connector='OR'), name='order_delivery_coordinates_together'),
        ),
    ]
