# Generated by Django 6.0.6 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_snapshot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'AWAITING_PAYMENT'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('DELIVERING', 'DELIVERING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
    ]
