# Generated by Django 6.0.6 on 2026-09-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_restaurant'),
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
    ]
