# Generated by Django 6.0.6 on 2026-07-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('restaurants', '0003_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='restaurants.restaurant'),
        ),
    ]
