# Generated by Django 6.0.6 on 2026-09-21

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0006_alter_menuitem_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("event_type", models.CharField(choices=[("served", "Recommendation served"), ("clicked", "Recommendation clicked"), ("added_to_cart", "Recommendation added to cart"), ("ordered", "Recommendation ordered")], max_length=20)),
                ("query", models.CharField(blank=True, default="", max_length=500)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("menu_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recommendation_events", to="restaurants.menuitem")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recommendation_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="recommendationevent",
            index=models.Index(fields=["request_id", "event_type"], name="ai_recommen_request_8592b7_idx"),
        ),
    ]