# Generated by Django 6.0.6 on 2026-09-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
