# Generated by Django 6.0.6 on 2026-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'CLIENT'), ('COURIER', 'COURIER'), ('ADMIN', 'ADMIN')], default='CLIENT', max_length=20),
        ),
    ]
