# Generated by Django 6.0.6 on 2026-08-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_verificationcode'),
        ('users', '0004_verificationcode'),
    ]

    operations = [
    ]
