# Generated by Django 6.0.6 on 2026-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260818_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password reset'), ('EMAIL_VERIFICATION', 'Email Verification')], default='EMAIL_VERIFICATION', max_length=32),
        ),

    ]
