# Generated by Django 6.0.6 on 2026-08-30 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_verificationcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatar_01', 'Avatar 01'), ('avatar_02', 'Avatar 02'), ('avatar_03', 'Avatar 03'), ('avatar_04', 'Avatar 04'), ('avatar_05', 'Avatar 05'), ('avatar_06', 'Avatar 06')], default='avatar_01', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('formatted_address', models.CharField(max_length=500)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('building', models.CharField(blank=True, default='', max_length=20)),
                ('apartment', models.CharField(blank=True, default='', max_length=20)),
                ('entrance', models.CharField(blank=True, default='', max_length=20)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, default='', max_length=500)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_delivery_address_per_user'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='delivery_address_coordinates_together')],
            },
        ),
    ]
