# Generated by Django 6.0.6 on 2026-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatar_01', 'Avatar 01'), ('avatar_02', 'Avatar 02'), ('avatar_03', 'Avatar 03'), ('avatar_04', 'Avatar 04'), ('avatar_05', 'Avatar 05'), ('avatar_06', 'Avatar 06'), ('avatar_07', 'Avatar 07')], default='avatar_01', max_length=20),
        ),
    ]
