# Generated by Django 6.0.6 on 2026-09-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RESTAURANT_VIEW', 'Restaurant View'), ('MENU_ITEM_VIEW', 'Menu Item View'), ('SEARCH', 'Search'), ('AI_SEARCH', 'Ai Search'), ('ADD_TO_CART', 'Add To Cart'), ('REMOVE_FROM_CART', 'Remove From Cart'), ('FAVORITE_RESTAURANT', 'Favorite Restaurant'), ('ORDER_COMPLETED', 'Order Completed'), ('REVIEW_CREATED', 'Review Created')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='users_usere_user_id_d3fb6e_idx'), models.Index(fields=['user', 'created_at'], name='users_usere_user_id_8d9ae5_idx')],
            },
        ),
    ]
