# Generated by Django 6.0.6 on 2026-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_avatar'),
        ('users', '0010_userevent'),
    ]

    operations = [
    ]
